package org.itmo.exceptions;

/**
 * Generated by unexpected errors during command checks
 */
public class CheckerException extends Exception {
    
    /**
     * @param exception information on the exception that has occurred
     */
    public CheckerException(Exception exception) {
        super(exception);
    }
}
