package org.itmo.exceptions;

/**
 * Generated by unexpected errors during command checks
 */
public class CheckerException extends Exception {
    
    /**
     *
     * @param message essage with additional info about exception
     */
    public CheckerException(String message) {
        super(message);
    }
    
    /**
     *
     * @param exception information on the exemption that has occurred
     */
    public CheckerException(Exception exception) {
        super(exception);
    }
}
